[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = { version = "4.2.0", features = ["blake3"] }
fibonacci-lib = { path = "../lib" }
